import { useMemo, useState } from 'react';
import { Autocomplete, Box, Button, Chip, Paper, Table, TableBody, TableCell, TableContainer, TableHead, TableRow, TextField, Typography } from '@mui/material';
import type { NodePatch, Snapshot } from '../shared/types';
import { analyze } from '../domain/catalog';
export function CatalogGrid({ state, busy, onPatch, onBack }: { state: Snapshot; busy: boolean; onPatch: (id: string, patch: NodePatch) => void; onBack: () => void }) {
  const [query, setQuery] = useState(''); const analysis = useMemo(() => analyze(state), [state]);
  const rows = analysis.active.filter(n => !query.trim() || `${n.name} ${n.sourcePath}`.toLocaleLowerCase().includes(query.trim().toLocaleLowerCase()));
  return <Box className="workspace"><Box className="page-heading"><Box><Typography sx={{ color: 'primary.main', fontSize: 11, fontWeight: 700, letterSpacing: 2 }}>CATALOG BULK EDIT</Typography><Typography variant="h4" sx={{ mt: 1, mb: 1 }}>登録内容を表で編集</Typography><Typography sx={{ color: 'text.secondary' }}>Excelの表のように、タイトル・カテゴリ・タグを行単位で設定できます。</Typography></Box><Button variant="outlined" onClick={onBack} autoFocus>← 登録設定へ戻る</Button></Box><Paper sx={{ p: 2, mt: 3 }}><TextField fullWidth label="名前・パスで絞り込み" value={query} onChange={e => setQuery(e.target.value)} /><Typography sx={{ color: 'text.secondary', fontSize: 11, mt: 1 }}>{rows.length.toLocaleString()} / {analysis.active.length.toLocaleString()} 件</Typography></Paper><TableContainer component={Paper} sx={{ mt: 2, maxHeight: 'calc(100vh - 310px)' }}><Table stickyHeader size="small"><TableHead><TableRow><TableCell sx={{ minWidth: 230 }}>対象</TableCell><TableCell sx={{ minWidth: 260 }}>タイトル</TableCell><TableCell sx={{ minWidth: 180 }}>カテゴリ</TableCell><TableCell sx={{ minWidth: 320 }}>タグ</TableCell></TableRow></TableHead><TableBody>{rows.map(n => <GridRow key={n.id} node={n} state={state} analysis={analysis} busy={busy} onPatch={onPatch} />)}</TableBody></Table></TableContainer></Box>;
}
function GridRow({ node, state, analysis, busy, onPatch }: { node: Snapshot['nodes'][number]; state: Snapshot; analysis: ReturnType<typeof analyze>; busy: boolean; onPatch: (id: string, patch: NodePatch) => void }) {
  const meta = analysis.metadata.get(node.id)!; const [title, setTitle] = useState(meta.title); const [tagIds, setTagIds] = useState(meta.tagIds); const isCatalog = node.mode !== 'dataset';
  return <TableRow hover><TableCell><Typography sx={{ fontWeight: 600, fontSize: 12 }}>{node.name}</Typography><Typography sx={{ fontSize: 10, color: 'text.secondary', overflowWrap: 'anywhere' }}>{node.sourcePath}</Typography><Chip size="small" label={isCatalog ? 'カタログ' : 'データセット'} variant="outlined" /></TableCell><TableCell><TextField fullWidth size="small" value={title} disabled={busy || (node.inherit && !isCatalog)} error={!title.trim()} onChange={e => setTitle(e.target.value)} onBlur={() => { if (title !== meta.title) onPatch(node.id, { title }); }} /></TableCell><TableCell>{isCatalog ? <TextField select fullWidth size="small" value={node.catalogCategoryId ?? ''} disabled={busy} onChange={e => onPatch(node.id, { catalogCategoryId: e.target.value || undefined })}><option value="">未分類</option>{state.categories.map(c => <option key={c.id} value={c.id}>{c.name}</option>)}</TextField> : <Typography sx={{ color: 'text.secondary', fontSize: 12 }}>—</Typography>}</TableCell><TableCell><Autocomplete multiple size="small" options={state.tags} getOptionLabel={t => t.label} value={state.tags.filter(t => tagIds.includes(t.id))} disabled={busy || (node.inherit && !isCatalog)} onChange={(_, values) => { const ids = values.map(t => t.id); setTagIds(ids); onPatch(node.id, { tagIds: ids }); }} renderInput={params => <TextField {...params} label="タグ" />} /></TableCell></TableRow>;
}
