import { useMemo, useState } from 'react';
import { Alert, Autocomplete, Box, Button, Chip, MenuItem, Paper, Stack, TextField, Typography } from '@mui/material';
import type { Snapshot } from '../shared/types';
import { analyze } from '../domain/catalog';
export function RegistrySearch({ state, onBack }: { state: Snapshot; onBack: () => void }) {
 const [query,setQuery]=useState(''); const [target,setTarget]=useState<'title'|'description'|'both'>('both'); const [tagId,setTagId]=useState(''); const [categoryId,setCategoryId]=useState(''); const [scope,setScope]=useState<'parents'|'catalogs'|'datasets'>('catalogs'); const [catalogId,setCatalogId]=useState(''); const a=useMemo(()=>analyze(state),[state]); const matches=(n:Snapshot['nodes'][number])=>{const q=query.trim().normalize('NFKC').toLowerCase();const m=a.metadata.get(n.id)!;const text=target==='title'?m.title:target==='description'?m.description:`${m.title}\u0000${m.description}`;return (!q||text.normalize('NFKC').toLowerCase().includes(q))&&(!tagId||m.tagIds.includes(tagId))&&(!categoryId||n.catalogCategoryId===categoryId)};
 const catalogs=a.catalogs.filter(matches); const results=useMemo(()=>{const base=scope==='parents'?a.catalogs.filter(n=>n.mode==='top'||n.mode==='standalone'):scope==='catalogs'?a.catalogs:a.active;return base.filter(n=>matches(n)&&(!catalogId||(n.mode==='dataset'&&(()=>{let p=n.parentId? a.byId.get(n.parentId):undefined;while(p&&p.id!==catalogId)p=p.parentId?a.byId.get(p.parentId):undefined;return !!p||n.parentId===catalogId})())));},[a,query,target,tagId,categoryId,scope,catalogId]);
 return <Box className="workspace"><Box className="page-heading"><Box><Typography sx={{color:'primary.main',fontSize:11,fontWeight:700,letterSpacing:2}}>REGISTERED CATALOG SEARCH</Typography><Typography variant="h4" sx={{mt:1,mb:1}}>登録データを検索</Typography><Typography sx={{color:'text.secondary'}}>階層・タイトル・説明・タグ・カテゴリで絞り込みます。</Typography></Box><Button variant="outlined" onClick={onBack}>← 登録設定へ戻る</Button></Box><Paper sx={{p:2,mt:3}}><Stack spacing={2}><Stack direction={{xs:'column',md:'row'}} spacing={2}><TextField fullWidth label="検索語" value={query} onChange={e=>setQuery(e.target.value)}/><TextField select label="検索対象" value={target} onChange={e=>setTarget(e.target.value as typeof target)}><MenuItem value="title">タイトル</MenuItem><MenuItem value="description">説明</MenuItem><MenuItem value="both">タイトルと説明</MenuItem></TextField><TextField select label="対象階層" value={scope} onChange={e=>setScope(e.target.value as typeof scope)}><MenuItem value="parents">親カタログのみ</MenuItem><MenuItem value="catalogs">子カタログを含む</MenuItem><MenuItem value="datasets">データセットを含む</MenuItem></TextField></Stack><Stack direction={{xs:'column',md:'row'}} spacing={2}><Autocomplete fullWidth options={state.tags} getOptionLabel={t=>t.label} value={state.tags.find(t=>t.id===tagId)??null} onChange={(_,t)=>setTagId(t?.id??'')} renderInput={p=><TextField {...p} label="タグで絞り込み"/>}/><TextField select fullWidth label="カテゴリで絞り込み" value={categoryId} onChange={e=>setCategoryId(e.target.value)}><MenuItem value="">すべてのカテゴリ</MenuItem>{state.categories.map(c=><MenuItem key={c.id} value={c.id}>{c.name}</MenuItem>)}</TextField></Stack></Stack></Paper>{scope==='datasets'&&<Paper sx={{p:2,mt:2}}><Typography sx={{fontWeight:700,mb:1}}>検索結果からカタログを選択</Typography><Stack direction="row" spacing={1} sx={{flexWrap:'wrap'}}>{catalogs.map(n=><Chip key={n.id} label={a.metadata.get(n.id)?.title||n.name} color={catalogId===n.id?'primary':'default'} variant={catalogId===n.id?'filled':'outlined'} onClick={()=>setCatalogId(catalogId===n.id?'':n.id)}/>)}{!catalogs.length&&<Typography sx={{fontSize:12,color:'text.secondary'}}>一致するカタログがありません。</Typography>}</Stack>{catalogId&&<Button size="small" onClick={()=>setCatalogId('')}>カタログ絞り込みを解除</Button>}</Paper>}<Typography sx={{color:'text.secondary',fontSize:11,mt:2}}>{results.length.toLocaleString()} 件</Typography>{!results.length?<Alert severity="info" sx={{mt:2}}>検索条件に一致する登録データはありません。</Alert>:<Stack spacing={1.5} sx={{mt:2}}>{results.map(n=>{const m=a.metadata.get(n.id)!;return <Paper key={n.id} sx={{p:2}}><Stack direction={{xs:'column',md:'row'}} spacing={1} sx={{justifyContent:'space-between'}}><Box><Typography sx={{fontWeight:700}}>{m.title}</Typography><Typography sx={{fontSize:12,overflowWrap:'anywhere'}}>{m.description||'説明なし'}<br/>{n.sourcePath}</Typography></Box><Stack direction="row" spacing={1}><Chip label={n.mode==='dataset'?'データセット':state.categories.find(c=>c.id===n.catalogCategoryId)?.name??'未分類'} variant="outlined"/></Stack></Stack></Paper>})}</Stack>}</Box>;
}
